#!/bin/bash
set -e

set -x
curl -L https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -
echo 'deb https://deb.nodesource.com/node_6.x jessie main' >> /etc/apt/sources.list
apt-get update
