#!/bin/bash
set -e

SITENAME=$1

cat <<NGINX_CONF
server {
  server_name $SITENAME;

  location / {
    return 301 https://\$host\$request_uri;
  }

  location /.well-known/acme-challenge {
    alias /opt/https/acme-challenge;
  }
}

server {
  listen 443 ssl;
  server_name $SITENAME;

  ssl_certificate /opt/https/certs/$SITENAME/fullchain.pem;
  ssl_certificate_key /opt/https/certs/$SITENAME/privkey.pem;
  include /opt/https/nginx/https.conf;
}
NGINX_CONF
